---
- name: Change Nginx port to 81
  replace:
    path: /etc/nginx/sites-available/default
    regexp: 'listen 80 default_server'
    replace: 'listen 81 default_server'
  notify: restart nginx service  # This line tells Ansible to trigger the handler
  become: yes